name: rojo
favicon: null
layout_spectrum: 0.74059
typography_spectrum: 0.98625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#7f7f7f'
    - '#ababab'
    - '#474747'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: engagement
    item: null
    url: null
